---
functional:
  - Должна быть доступна регистрация и авторизация через электронную почту, профиль на GitHub или Discord;
  - Должна быть возможность провести игру без регистрации;
  - Должна быть возможность выбора языка программирования для игры;
  - Должен быть выбор уровня сложности;
  - Должна быть возможность играть с игроками, ботом, а также черенз ссылку-приглашение с другим пользователем;
  - Пользователи должны иметь возможность общаться в чате;
  - В проекте должна быть введена рейтинговая система на основе проведенных поединков, у пользователей должен быть доступ к статистике;

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы;
  - Сайт должен быть безопасным и защищать данные пользователя;
  - Сайт должен быть удобным на мобильном устройстве;
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров;
  - Сайт должен предоставлять пользователю возможность выбора языка интерфейса и самой игры;

implicit:
  - На сервисе должны быть инструкция/подсказки/описание игры для новых пользователей;
  - Должна быть возможность просмотра архива завершенных игр;
  - У разработчиков должна быть возможность принять участие в доработке функционала сайта и внедрении новых возможностей.